[package]
name = "suik"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.8.4" }
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"                               # 绑定 wasm 和 JavaScript 的库
[lib]
crate-type = ["cdylib"] # 为了支持 WASM，设置 crate 类型为 cdylib
